En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij}) et (B_{ij}) notée $A+B$  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c_{ij}=a_{ij}+b_{ij}$


In [1]:
#without numpy
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)


#with numpy 
import numpy as np

nX=np.array(X)
nY=np.array(Y)

print(nX+nY)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]
[[17 15  4]
 [10 12  9]
 [11 13 18]]


Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

check website https://www.journaldev.com/32966/numpy-matrix-multiplication

In [4]:
import numpy as np

A = np.array([[1, 2],
                 [3, 4]])
B = np.array([[5, 6],
                 [7, 8]])

#matrix product

arr_result = np.matmul(A, B)

print(f'Matrix Product of A and B is A*B:\n{arr_result}')

arr_result = np.matmul(B, A)

print(f'Matrix Product of B and A is B*A:\n{arr_result}')

#meme chose
arr_result = np.dot(A, B)

print(f'Dot Product of A and B is:\n{arr_result}')

arr_result = np.dot(B, A)

print(f'Dot Product of B and A is:\n{arr_result}')

#be careful of this: does not give matrix maltiplication check website above
# multiply Element Wise 
arr_result = np.multiply(A, B)

print(arr_result)
#meme chose
arr_result=A*B

print(arr_result)



Matrix Product of A and B is:
[[19 22]
 [43 50]]
Matrix Product of B and A is:
[[23 34]
 [31 46]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [ ]:
check https://en.wikipedia.org/wiki/Stochastic_matrix

In [14]:
P=np.array([[0.3,0.7],[0.7,0.3]])

def eststochastique(P):
    etat_nonnegative=(P>0).all()
    if not etat_nonnegative:
        print("there are zeros or negative numbers in matrix")
        return False
    #find if sum of columns is 1
    sommecolonne=np.sum(P,axis=1)
    #print(sommecolonne)
    etat_colonne=(sommecolonne == 1).all()
    if etat_colonne:
        print("left stochastic matrix")
    #find if sum of rows is 1
    sommeligne=np.sum(P,axis=0)
    #print(sommeligne)
    etat_ligne=(sommeligne == 1).all() 
    if etat_ligne:
        print("right stochastic matrix")
    print(etat_ligne)
    #if sum of column or row is 1 then it is stochastic matrix
    etat=etat_ligne or etat_colonne
    
    return etat

eststochastique(P)

left stochastic matrix
right stochastic matrix
True


True

In [15]:
def estbistochastique(P):
    etat_nonnegative=(P>0).all()
    if not etat_nonnegative:
        print("there are zeros or negative numbers in matrix")
        return False
    #find if sum of columns is 1
    sommecolonne=np.sum(P,axis=1)
    #print(sommecolonne)
    etat_colonne=(sommecolonne == 1).all()
    if etat_colonne:
        print("left stochastic matrix")
    #find if sum of rows is 1
    sommeligne=np.sum(P,axis=0)
    #print(sommeligne)
    etat_ligne=(sommeligne == 1).all() 
    if etat_ligne:
        print("right stochastic matrix")
    print(etat_ligne)
    #if sum of column or row is 1 then it is stochastic matrix
    etat=etat_ligne and etat_colonne
    if etat:
        print("This matrix is bistochastique")
    return etat

estbistochastique(P)

left stochastic matrix
right stochastic matrix
True
This matrix is bistochastique


True

h stable de G --> h*G=h--> h*G-h=0

In [25]:
G=np.array([[1/4,3/4],[1/8,7/8]])
h=np.array([1/7,6/7])

def vecteurstable(G, h):
    mat=np.matmul(h, G)-h
    vectstable=(mat==0).all()
    if vectstable:
        print("h is stable vector of G")
    return vectstable

vecteurstable(G, h)

h is stable vector of G


True

Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [ ]:
B=np.transpose(A)

Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)

In [43]:

def permutation(M,n):
    l,c=M.shape
    A=np.zeros((l,1))+n
    Ma = np.hstack((M[:,:0], A, M[:,0:]))
    sortie=Ma
    for i in range(1,c+1):
        Ma = np.hstack((M[:,:i], A, M[:,i:]))
        sortie=np.vstack((sortie,Ma))
    print(sortie)

M=np.array([[0,1],[5,6]])
n=3

permutation(M,n)

[[3. 0. 1.]
 [3. 5. 6.]
 [0. 3. 1.]
 [5. 3. 6.]
 [0. 1. 3.]
 [5. 6. 3.]]
